
name: RunTests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
      
env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:   
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
          with:
            lfs: true        

        - name: Setup Environment
          run: |
            mkdir Tmp
            mv Editor Tmp/
            mv Runtime Tmp/
            mv Tests Tmp/
            mv package.json Tmp/package.json         

        - name: Run Tests
          uses: game-ci/unity-test-runner@v4
          env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          with:             
            packageMode: true
            projectPath: Tmp/
            testMode: all
            unityVersion: 2022.3.17f1
            

